- name: Build Docker Image and Check Health
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build docker image
      command: sudo docker build -t kiranp23/webapp:{{ image_version }} .

    - name: Run Docker image
      command: sudo docker run -p 7010:8080 --name webapp -d kiranp23/webapp:{{ image_version }}

    - name: Get the external ip
      command: curl http://169.254.169.254/latest/meta-data/public-ipv4
      args:
        warn: false
      register: result
    - debug: msg={{ result.stdout }}

    - set_fact: external_ip={{ result.stdout }}

    - pause:
       seconds: 30
      
    - name: Checking url status.. wait for 200
      uri: url=http://{{ external_ip }}:7010/webapp/index.html
      register: result
      until: result.status == 200
      retries: 5
      delay: 5
    - debug: msg="Url staus is {{ result.status }}"

    - name: Stopping container
      command: sudo docker stop webapp

    - name: Removing container
      command: sudo docker rm webapp

    - name: Pushing image to dockerhub
      command: sudo docker push kiranp23/webapp:{{ image_version }}

    - name: Removing image from local
      command: sudo docker rmi kiranp23/webapp:{{ image_version }}
      
    - name: Clean docker files from local system
      command: sudo docker system prune --all -f
