- name: Build Docker Image and Check Health
  hosts: all
  gather_facts: no

  tasks:
    - name: Build docker image
      command: docker build -t kiranp23/webapp:{{ image_version }} .

    - name: Run Docker image
      command: docker run -p 7010:8080 --name webapp -d kiranp23/webapp:{{ image_version }}

    - name: Get the external ip
      command: curl http://169.254.169.254/latest/meta-data/public-ipv4
      args:
        warn: false
      register: result
    - debug: msg={{ result.stdout }}

    - set_fact: external_ip={{ result.stdout }}

    - pause:
       seconds: 30
      
    - name: Checking url status.. wait for 200
      uri: url=http://{{ external_ip }}:7010/webapp/index.html
      register: result
      until: result.status == 200
      retries: 5
      delay: 5
    - debug: msg="Url staus is {{ result.status }}"

    - name:  stopping container
      command: docker stop webapp

    - name: removing container
      command: docker rm webapp

    - debug: msg="Pushing image to dockerhub"
    - name: pushing image to docker
      command: docker push kiranp23/webapp:{{ image_version }}

    - debug: msg="Removing local image"
    - name: removing image from local
      command: docker rmi kiranp23/webapp:{{ image_version }}
