- name: Copy RSA Key to master node
  hosts: k8smaster
  become: yes 
  tasks:
     - name: Set authorized key for user ubuntu copying it from current user
       authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: Copy RSA Key to workernodes
  hosts: k8sworker
  become: yes
  tasks:
     - name: Set authorized key for user ubuntu copying it from current user
       authorized_key:
            user: ubuntu
            state: present
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
